sudo: false
arch:
   - amd64
   - ppc64le
language: go
go_import_path: go.uber.org/atomic
go_import_path: github.com/stretchr/testify/assert

env:
  global:
    - GO113MODULE=on

matrix:
  include:
  - go: oldstable
  - go: stable
    env: LINT=1

cache:
  directories:
    - vendor

before_install:
  - go version

script:
  - test -z "$LINT" || make lint
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
